name: "Cherry Pick Remote"
description: "Cherry pick commits from remote repository."

inputs:
  repository:
    description: "The GitHub repository to cherry pick commits from."
    required: true
  branch:
    description: "The name of the branch to rebase the cherry picked commits to."
    default: "main"
  remote-branch:
    description: "The name of the branch of remote repository to cherry pick commits from."
    default: "main"
  include-paths:
    description: "The paths within the repository files to consider for cherry picks. Must be JSON serialized array of string."
    default: null
  exclude-paths:
    description: "The paths within the repository files to exclude from cherry picks. Must be JSON serialized array of string."
    default: null
  credentials:
    description: "The Git credentials to set for authorization with remote server."
    required: true
  username:
    description: "The username to use as an author for cherry picking commits."
    required: true
  email:
    description: "The email to use as an author for cherry picking commits."
    required: true

runs:
  using: "node12"
  main: "dist/index.js" 
