name: "Cherry Pick Remote"
description: "Cherry pick commits from remote repository."

inputs:
  repository:
    description: "The GitHub repository to cherry pick commits from. For example: weibeu/cherry-pick-remote-trigger."
    required: true
  branch:
    description: "The name of the branch to rebase the cherry picked commits to."
    default: "main"
  path:
    description: "The path within the repository files to consider for cherry picks."
    default: "."
  token:
    description: "Personal access token (PAT) to run authenticated git commands."
    default: ${{ github.token }}
  credentials:
    description: "Personal access token (PAT) to run authenticated git commands."
    default: ${{ github.token }}
  username:
    description: "The username to use for cherry picking commits."
    required: true
  email:
    description: "The email to use for cherry picking commits."
    required: true

runs:
  using: "node12"
  main: "dist/index.js" 
